#!/bin/bash
set -euo pipefail

# skill.sh — build / install / verify / check the moonklabs-skills marketplace.
# Walks every category plugin (fundraising/, gtm-strategy/, finance-metrics/,
# gov-apply/, dev-workflow/, design-system/) and produces:
#   dist/AGENTS.md                     — aggregated index for Codex AGENTS.md
#   dist/codex-prompts/<skill>.md      — one prompt per skill (flat)
#
# Requires: yq (YAML), jq (JSON). macOS: brew install yq jq
# Usage:
#   ./skill.sh build     — parse all categories, generate dist artifacts
#   ./skill.sh install   — copy dist/codex-prompts/*.md to ~/.codex/prompts/
#   ./skill.sh verify    — run automated acceptance tests (PASS/FAIL)
#   ./skill.sh check     — lint plugin.json + SKILL.md across categories

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="${REPO_ROOT}/dist"
CODEX_PROMPTS_DIR="${HOME}/.codex/prompts"
MARKETPLACE_JSON="${REPO_ROOT}/.claude-plugin/marketplace.json"

# ============================================================================
# Dependency check
# ============================================================================
check_dependencies() {
  local missing=0
  for cmd in yq jq; do
    if ! command -v "$cmd" &> /dev/null; then
      echo "Error: $cmd not found. Install with: brew install $cmd"
      missing=$((missing+1))
    fi
  done
  if [[ $missing -gt 0 ]]; then
    exit 1
  fi
}

# ============================================================================
# Discover category plugin directories from marketplace.json (relative paths).
# Fallback: walk first-level dirs that contain .claude-plugin/plugin.json.
# ============================================================================
list_category_plugins() {
  if [[ -f "${MARKETPLACE_JSON}" ]]; then
    jq -r '.plugins[].source' "${MARKETPLACE_JSON}" | sed "s|^\./||"
  else
    for d in "${REPO_ROOT}"/*/; do
      [[ -f "${d}.claude-plugin/plugin.json" ]] && basename "${d%/}"
    done
  fi
}

# ============================================================================
# Extract SKILL.md YAML frontmatter into description/author/version.
# yq fails on the markdown body, so slice the frontmatter block first.
# ============================================================================
parse_skill_frontmatter() {
  local skill_md="$1"
  local frontmatter description author version

  frontmatter=$(awk 'BEGIN{n=0} /^---[[:space:]]*$/{n++; if(n==2) exit; next} n==1 {print}' "${skill_md}")

  description=""
  author="Moonklabs"
  version="1.0.0"

  if [[ -n "${frontmatter}" ]]; then
    description=$(printf '%s\n' "${frontmatter}" | yq eval '.description // ""' - 2>/dev/null)
    author=$(printf '%s\n' "${frontmatter}" | yq eval '.author // "Moonklabs"' - 2>/dev/null)
    version=$(printf '%s\n' "${frontmatter}" | yq eval '.version // "1.0.0"' - 2>/dev/null)
  fi

  [[ -z "${description}" || "${description}" == "null" ]] && description="See SKILL.md for details."
  [[ -z "${author}" || "${author}" == "null" ]] && author="Moonklabs"
  [[ -z "${version}" || "${version}" == "null" ]] && version="1.0.0"

  printf '%s\t%s\t%s' "${description}" "${author}" "${version}"
}

# ============================================================================
# build: generate dist/AGENTS.md + dist/codex-prompts/*.md
# ============================================================================
build() {
  check_dependencies
  echo "Building AGENTS.md and Codex prompts across categories..."
  rm -rf "${DIST_DIR}/codex-prompts"
  mkdir -p "${DIST_DIR}/codex-prompts"

  cat > "${DIST_DIR}/AGENTS.md" << 'EOF'
# Moonklabs Skills Marketplace

Auto-generated by `skill.sh build`. Do not edit directly.

## Skills by Category

EOF

  local total=0
  while IFS= read -r category; do
    [[ -z "${category}" ]] && continue
    local category_dir="${REPO_ROOT}/${category}"
    local plugin_json="${category_dir}/.claude-plugin/plugin.json"
    [[ ! -f "${plugin_json}" ]] && continue

    local category_name category_desc
    category_name=$(jq -r '.name' "${plugin_json}")
    category_desc=$(jq -r '.description' "${plugin_json}")

    {
      echo "### ${category_name}"
      echo ""
      echo "${category_desc}"
      echo ""
    } >> "${DIST_DIR}/AGENTS.md"

    for skill_dir in "${category_dir}/skills"/*; do
      [[ ! -d "${skill_dir}" ]] && continue
      local skill_name skill_md description author version
      skill_name="$(basename "${skill_dir}")"
      skill_md="${skill_dir}/SKILL.md"
      if [[ ! -f "${skill_md}" ]]; then
        echo "Warning: ${category}/${skill_name} has no SKILL.md, skipping."
        continue
      fi

      IFS=$'\t' read -r description author version < <(parse_skill_frontmatter "${skill_md}")

      # Codex prompt: one flat file per skill.
      {
        echo "# ${skill_name}"
        echo ""
        echo "## Category"
        echo "${category} (${category_name})"
        echo ""
        echo "## Description"
        echo "${description}"
        echo ""
        echo "## Author"
        echo "${author}"
        echo ""
        echo "## Version"
        echo "${version}"
        echo ""
        echo "## Full Documentation"
        echo "See \`${category}/skills/${skill_name}/SKILL.md\` in the repository."
      } > "${DIST_DIR}/codex-prompts/${skill_name}.md"

      {
        echo "- **${skill_name}** — ${description}"
        echo "  - Location: \`${category}/skills/${skill_name}/\` · Author: ${author} · Version: ${version}"
      } >> "${DIST_DIR}/AGENTS.md"
      total=$((total+1))
    done
    echo "" >> "${DIST_DIR}/AGENTS.md"
  done < <(list_category_plugins)

  echo "Build complete — ${total} skills."
  echo "  - ${DIST_DIR}/AGENTS.md"
  echo "  - ${DIST_DIR}/codex-prompts/ ($(ls -1 "${DIST_DIR}/codex-prompts" | wc -l | tr -d ' ') files)"
}

# ============================================================================
# install: copy Codex prompts to ~/.codex/prompts/
# ============================================================================
install() {
  if [[ ! -d "${DIST_DIR}/codex-prompts" ]]; then
    echo "Error: dist/codex-prompts not found. Run './skill.sh build' first."
    exit 1
  fi
  mkdir -p "${CODEX_PROMPTS_DIR}"
  echo "Installing Codex prompts to ${CODEX_PROMPTS_DIR}..."
  cp "${DIST_DIR}/codex-prompts"/*.md "${CODEX_PROMPTS_DIR}/"
  local count
  count=$(ls -1 "${DIST_DIR}/codex-prompts" | wc -l | tr -d ' ')
  echo "Installed ${count} prompt files."
}

# ============================================================================
# verify: automated acceptance tests (PASS/FAIL)
# ============================================================================
verify() {
  check_dependencies
  echo "Running verification suite..."
  local passed=0 failed=0

  # 1. marketplace.json validity
  if [[ -f "${MARKETPLACE_JSON}" ]] && jq -e '.plugins | length >= 1' "${MARKETPLACE_JSON}" >/dev/null 2>&1; then
    echo "[PASS] marketplace.json: valid with $(jq '.plugins | length' "${MARKETPLACE_JSON}") plugins"
    passed=$((passed+1))
  else
    echo "[FAIL] marketplace.json: missing or invalid"
    failed=$((failed+1))
  fi

  # 2. Every category has plugin.json
  local missing_manifests=0
  while IFS= read -r category; do
    [[ -z "${category}" ]] && continue
    [[ ! -f "${REPO_ROOT}/${category}/.claude-plugin/plugin.json" ]] && {
      echo "  - missing: ${category}/.claude-plugin/plugin.json"
      missing_manifests=$((missing_manifests+1))
    }
  done < <(list_category_plugins)
  if [[ ${missing_manifests} -eq 0 ]]; then
    echo "[PASS] All category plugins have .claude-plugin/plugin.json"
    passed=$((passed+1))
  else
    echo "[FAIL] ${missing_manifests} category plugin(s) missing plugin.json"
    failed=$((failed+1))
  fi

  # 3. Every skill has SKILL.md
  local missing_skills=0
  while IFS= read -r category; do
    [[ -z "${category}" ]] && continue
    local skills_dir="${REPO_ROOT}/${category}/skills"
    [[ ! -d "${skills_dir}" ]] && continue
    for s in "${skills_dir}"/*/; do
      [[ -d "${s}" && ! -f "${s}SKILL.md" ]] && {
        echo "  - missing: ${category}/skills/$(basename "${s%/}")/SKILL.md"
        missing_skills=$((missing_skills+1))
      }
    done
  done < <(list_category_plugins)
  if [[ ${missing_skills} -eq 0 ]]; then
    echo "[PASS] All skills have SKILL.md"
    passed=$((passed+1))
  else
    echo "[FAIL] ${missing_skills} skill(s) missing SKILL.md"
    failed=$((failed+1))
  fi

  # 4. plugin.json skills[].source references resolve to real dirs
  local bad_sources=0
  while IFS= read -r category; do
    [[ -z "${category}" ]] && continue
    local manifest="${REPO_ROOT}/${category}/.claude-plugin/plugin.json"
    [[ ! -f "${manifest}" ]] && continue
    while IFS= read -r src; do
      [[ -z "${src}" ]] && continue
      local resolved="${REPO_ROOT}/${category}/${src#./}"
      [[ ! -d "${resolved}" ]] && {
        echo "  - missing: ${category} → ${src}"
        bad_sources=$((bad_sources+1))
      }
    done < <(jq -r '.skills[].source' "${manifest}" 2>/dev/null)
  done < <(list_category_plugins)
  if [[ ${bad_sources} -eq 0 ]]; then
    echo "[PASS] Every plugin.json skill source resolves to a real directory"
    passed=$((passed+1))
  else
    echo "[FAIL] ${bad_sources} skill source(s) missing"
    failed=$((failed+1))
  fi

  # 5. build succeeds
  if build >/dev/null 2>&1; then
    echo "[PASS] skill.sh build: dist/AGENTS.md generated"
    passed=$((passed+1))
  else
    echo "[FAIL] skill.sh build: build failed"
    failed=$((failed+1))
  fi

  # 6. AGENTS.md sanity — at least one representative skill per category
  local probes=(fundraising-process gtm-strategy startup-metrics kb-structure git-submodule-manager design-md)
  local agents_missing=0
  for p in "${probes[@]}"; do
    grep -q "${p}" "${DIST_DIR}/AGENTS.md" 2>/dev/null || {
      echo "  - probe missing in AGENTS.md: ${p}"
      agents_missing=$((agents_missing+1))
    }
  done
  if [[ ${agents_missing} -eq 0 ]]; then
    echo "[PASS] AGENTS.md contains every category probe skill"
    passed=$((passed+1))
  else
    echo "[FAIL] AGENTS.md missing ${agents_missing} probe skill(s)"
    failed=$((failed+1))
  fi

  # 7. Codex prompts unique (flat namespace collision check)
  local total_skills unique_prompts
  total_skills=$(list_category_plugins | while read -r c; do
    [[ -n "${c}" ]] && find "${REPO_ROOT}/${c}/skills" -maxdepth 2 -name SKILL.md 2>/dev/null
  done | wc -l | tr -d ' ')
  unique_prompts=$(ls -1 "${DIST_DIR}/codex-prompts" 2>/dev/null | wc -l | tr -d ' ')
  if [[ "${total_skills}" -eq "${unique_prompts}" ]]; then
    echo "[PASS] Codex prompt count matches skill count (${unique_prompts})"
    passed=$((passed+1))
  else
    echo "[FAIL] Prompt count mismatch: ${total_skills} skills vs ${unique_prompts} prompts (name collision?)"
    failed=$((failed+1))
  fi

  echo ""
  echo "============================================================================"
  echo "Summary: ${passed} PASS, ${failed} FAIL"
  if [[ ${failed} -eq 0 ]]; then
    echo "All automated tests passed!"
    exit 0
  else
    exit 1
  fi
}

# ============================================================================
# check: lint plugin.json + SKILL.md
# ============================================================================
check() {
  echo "Checking marketplace integrity..."
  local failed=0
  [[ ! -f "${MARKETPLACE_JSON}" ]] && { echo "Error: ${MARKETPLACE_JSON} not found."; exit 1; }

  while IFS= read -r category; do
    [[ -z "${category}" ]] && continue
    local manifest="${REPO_ROOT}/${category}/.claude-plugin/plugin.json"
    if [[ ! -f "${manifest}" ]]; then
      echo "Error: ${category}/.claude-plugin/plugin.json missing"
      failed=$((failed+1))
      continue
    fi
    jq empty "${manifest}" 2>/dev/null || { echo "Error: ${manifest} is not valid JSON"; failed=$((failed+1)); }

    for skill_dir in "${REPO_ROOT}/${category}/skills"/*/; do
      [[ ! -d "${skill_dir}" ]] && continue
      local skill_md="${skill_dir}SKILL.md"
      if [[ ! -f "${skill_md}" ]]; then
        echo "Error: ${category}/$(basename "${skill_dir%/}") missing SKILL.md"
        failed=$((failed+1))
      elif ! head -n 1 "${skill_md}" | grep -q "^---"; then
        echo "Warning: ${category}/$(basename "${skill_dir%/}") SKILL.md missing YAML delimiter."
      fi
    done
  done < <(list_category_plugins)

  [[ ${failed} -gt 0 ]] && { echo "Check failed: ${failed} error(s)."; exit 1; }
  echo "Check passed."
}

# ============================================================================
# Main
# ============================================================================
main() {
  local command="${1:-build}"
  case "${command}" in
    build)   build ;;
    install) install ;;
    verify)  verify ;;
    check)   check ;;
    *)
      cat <<USAGE
Usage: ${0} {build|install|verify|check}

Commands:
  build   - Parse all category plugins, generate dist/AGENTS.md + Codex prompts
  install - Copy Codex prompts to ~/.codex/prompts/
  verify  - Run automated acceptance tests (PASS/FAIL)
  check   - Lint plugin.json + SKILL.md files
USAGE
      exit 1
      ;;
  esac
}

main "$@"
